# Generated by Django 2.1.7 on 2019-03-24 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('article', '0002_articlepost_total_views'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlepost',
            table='文章',
        ),
    ]
