# Generated by Django 2.1.7 on 2019-03-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/%Y%m%d%H%M%S/'),
        ),
    ]
